#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Wed Jun 04 20:12:07 IST 2025
entry.Cryptography.enc=enc
category.name=Cryptography
tooltip.Cryptography.enc=enc
