#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Wed Jun 04 19:59:33 IST 2025
tooltip.UDN.Encryption=Encryption
category.name=UserDefineNode
entry.UDN.Encryption=Encryption
