#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Mon Jun 30 18:48:22 IST 2025
Property.iss=iss
Property.keyFile=keyFile
Property.expTime=expTime
InTerminal.in=in
Property.algo=algo
Property.value=value
OutTerminal.out=out
Property.key=key
Property.sub=sub
algo.HS256=HS256
Group.Claims=Claims
Property.claims=claims
algo.ES256=ES256
OutTerminal.failure=failure
JWTGen=JWTGen
algo.RS256=RS256
Group.Basic=Basic
