#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Fri Jun 06 13:45:41 IST 2025
Property.Key=Key
Algo.DES=DES
OutTerminal.Failure=Failure
Algo.AES=AES
InTerminal.in=in
Encryption=Encryption
Property.Algo=Algo
Group.Basic=Basic
OutTerminal.out=out
