#
#Thu Jun 26 16:03:59 IST 2025
bin.includes=META-INF/,**/*.msgnode,**/*.templatemsgnode,**/*.msgflow,**/*.properties,**/*.custom,**/*.esql,**/*.map,**/*.msgmap,HelpContexts.xml,palette.xmi,plugin.xml,icons/,.,generated/
source..=src/
output..=bin/
