<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema 
xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" 
xmlns:ref="http://www.ibm.com/dfdl/ISO8583Types" 
xmlns:ref1="http://www.ibm.com/dfdl/ISO8583Format">
        
  <import namespace="http://www.ibm.com/dfdl/ISO8583Format" schemaLocation="Common/ISO8583Format.xsd"/>
      
  <import namespace="http://www.ibm.com/dfdl/ISO8583Types" schemaLocation="Common/ISO8583Types.xsd"/>
      
  <element ibmSchExtn:docRoot="true" name="ISO8583">
        
    <complexType>
            
      <sequence>
        <element name="field1" type="string"/>
        <element name="field2" type="string"/>
        <element name="field3" type="string"/>
      </sequence>
          
    </complexType>
      
  </element>
  
</schema>
