#
#Fri Jun 27 16:01:18 IST 2025
bin.includes=META-INF/,**/*.msgnode,**/*.templatemsgnode,**/*.msgflow,**/*.properties,**/*.custom,**/*.esql,**/*.map,**/*.msgmap,HelpContexts.xml,palette.xmi,plugin.xml,icons/,.,generated/
source..=src/
output..=bin/
